apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  ports:
    - port: {{ .Values.appPort }}
      name: http
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: simple-app